name: alvorecer
description: App Alvorecer - Bíblia, Devocionais e IA Bíblica
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Necessário para suporte a internacionalização (Xcode exige)
  flutter_localizations:
    sdk: flutter

  # Firebase Core e Autenticação
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # UI e utilitários
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  # Estado e formulários
  provider: ^6.1.2
  intl: ^0.18.1
  shared_preferences: ^2.2.3
  go_router: ^14.6.2
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Geração de localizações automáticas
  generate: true

  assets:
    - assets/images/
    - assets/data/bible/