// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-8iqJAdh587_eoJPVaON4U1ULkkLqMYU',
    appId: '1:524745924262:web:6b53d92e27c125f4fc9e67',
    messagingSenderId: '524745924262',
    projectId: 'alvorecerflutterapp',
    authDomain: 'alvorecerflutterapp.firebaseapp.com',
    storageBucket: 'alvorecerflutterapp.firebasestorage.app',
    measurementId: 'G-9TWHT89TDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuLiqf0bgjJ4PGjcnMRcbnWbXhqowgTHU',
    appId: '1:524745924262:android:fbce7617f427f10ffc9e67',
    messagingSenderId: '524745924262',
    projectId: 'alvorecerflutterapp',
    storageBucket: 'alvorecerflutterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhczG-AUxU5MkztjOBtgAi81gmki13qIs',
    appId: '1:524745924262:ios:f13b42ff03478320fc9e67',
    messagingSenderId: '524745924262',
    projectId: 'alvorecerflutterapp',
    storageBucket: 'alvorecerflutterapp.firebasestorage.app',
    iosClientId: '524745924262-2653gj6gh542dh227ma41tquq3f8md34.apps.googleusercontent.com',
    iosBundleId: 'com.example.alvorecerFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhczG-AUxU5MkztjOBtgAi81gmki13qIs',
    appId: '1:524745924262:ios:f13b42ff03478320fc9e67',
    messagingSenderId: '524745924262',
    projectId: 'alvorecerflutterapp',
    storageBucket: 'alvorecerflutterapp.firebasestorage.app',
    iosClientId: '524745924262-2653gj6gh542dh227ma41tquq3f8md34.apps.googleusercontent.com',
    iosBundleId: 'com.example.alvorecerFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-8iqJAdh587_eoJPVaON4U1ULkkLqMYU',
    appId: '1:524745924262:web:bab9c6d38c50710cfc9e67',
    messagingSenderId: '524745924262',
    projectId: 'alvorecerflutterapp',
    authDomain: 'alvorecerflutterapp.firebaseapp.com',
    storageBucket: 'alvorecerflutterapp.firebasestorage.app',
    measurementId: 'G-49FVBQFRJW',
  );

}